const axios = require('axios');
const patients = [
  {
    first_name: 'Juan',
    middle_name: 'Agoncillo',
    last_name: 'Dela Cruz',
    birthdate: '1992-05-15',
    birthplace: 'Manila',
    age: 33,
    sex: 'Male',
    address: '123 Rizal St, Quezon City',
    religion: 'Roman Catholic',
    ethnicity: 'Tagalog',
    chief_complaints: 'Persistent fever and dry cough',
    room_no: '402',
    bed_no: 'A',
    user_id: 1,
    admission_date: '2026-01-04',
    contact_name: 'Maria Dela Cruz',
    contact_relationship: 'Spouse',
    contact_number: '09171234567',
  },
  {
    first_name: 'Elena',
    middle_name: 'Santos',
    last_name: 'Guevarra',
    birthdate: '1958-11-20',
    birthplace: 'Vigan, Ilocos Sur',
    age: 67,
    sex: 'Female',
    address: 'Unit 704, Sky Tower, Makati',
    religion: 'Christian',
    ethnicity: 'Ilocano',
    chief_complaints: 'Chest pain and shortness of breath',
    room_no: 'ICU-1',
    bed_no: '01',
    user_id: 1,
    admission_date: '2026-02-14',
    contact_name: 'Ricardo Guevarra',
    contact_relationship: 'Son',
    contact_number: '09189876543',
  },
  {
    first_name: 'Baby Boy',
    middle_name: 'Luz',
    last_name: 'Mercado',
    birthdate: '2026-01-10',
    birthplace: 'Antipolo, Rizal',
    age: 0,
    sex: 'Male',
    address: 'Purok 4, Antipolo, Rizal',
    religion: 'Roman Catholic',
    ethnicity: 'Tagalog',
    chief_complaints: 'Severe dehydration and vomiting',
    room_no: 'Pedia-10',
    bed_no: '04',
    user_id: 1,
    admission_date: '2026-02-20',
    contact_name: 'Angela Mercado',
    contact_relationship: 'Mother',
    contact_number: '09225550011',
  },
  {
    first_name: 'Siti',
    middle_name: 'Aminah',
    last_name: 'Usman',
    birthdate: '1985-03-12',
    birthplace: 'Jolo, Sulu',
    age: 40,
    sex: 'Female',
    address: 'B8 L12, Golden Village, Zamboanga',
    religion: 'Islam',
    ethnicity: 'Tausug',
    chief_complaints: 'Scheduled C-Section',
    room_no: 'OB-2',
    bed_no: 'B',
    user_id: 1,
    admission_date: '2026-01-15',
    contact_name: 'Nasser Usman',
    contact_relationship: 'Brother',
    contact_number: '09991112233',
  },
  {
    first_name: 'Robert',
    middle_name: 'James',
    last_name: 'Wilson',
    birthdate: '1975-07-04',
    birthplace: 'California, USA',
    age: 50,
    sex: 'Male',
    address: 'Subic Bay Freeport Zone',
    religion: 'Protestant',
    ethnicity: 'Caucasian',
    chief_complaints: 'Fractured leg from fall',
    room_no: '205',
    bed_no: '02',
    user_id: 1,
    admission_date: '2026-02-28',
    contact_name: 'Sarah Wilson',
    contact_relationship: 'Sister',
    contact_number: '09154443322',
  },
  {
    first_name: 'Ming',
    middle_name: 'Yao',
    last_name: 'Chen',
    birthdate: '1998-12-30',
    birthplace: 'Manila',
    age: 27,
    sex: 'Male',
    address: 'Binondo, Manila',
    religion: 'Buddhist',
    ethnicity: 'Chinese-Filipino',
    chief_complaints: 'Abdominal pain and nausea',
    room_no: '301',
    bed_no: '15',
    user_id: 1,
    admission_date: '2026-01-22',
    contact_name: 'Lin Chen',
    contact_relationship: 'Father',
    contact_number: '09162223344',
  },
  {
    first_name: 'Fatima',
    middle_name: 'K.',
    last_name: 'Musa',
    birthdate: '1994-06-21',
    birthplace: 'Maguindanao',
    age: 31,
    sex: 'Female',
    address: 'Cotabato City',
    religion: 'Islam',
    ethnicity: 'Maguindanaon',
    chief_complaints: 'Severe migraine and blurred vision',
    room_no: '112',
    bed_no: 'A1',
    user_id: 1,
    admission_date: '2026-03-01',
    contact_name: 'Ibrahim Musa',
    contact_relationship: 'Husband',
    contact_number: '09278889900',
  },
  {
    first_name: 'Mateo',
    middle_name: 'Gomez',
    last_name: 'Salvador',
    birthdate: '2015-09-09',
    birthplace: 'Davao City',
    age: 10,
    sex: 'Male',
    address: 'Davao City, Proper',
    religion: 'Roman Catholic',
    ethnicity: 'Bisaya',
    chief_complaints: 'High fever and joint pain',
    room_no: 'Pedia-05',
    bed_no: '12',
    user_id: 1,
    admission_date: '2026-02-08',
    contact_name: 'Liza Salvador',
    contact_relationship: 'Mother',
    contact_number: '09451114477',
  },
  {
    first_name: 'Grace',
    middle_name: 'Pua',
    last_name: 'Tan',
    birthdate: '1962-01-15',
    birthplace: 'Cebu City',
    age: 64,
    sex: 'Female',
    address: 'Cebu Business Park',
    religion: 'Roman Catholic',
    ethnicity: 'Chinese',
    chief_complaints: 'Uncontrolled hypertension',
    room_no: '505',
    bed_no: '05',
    user_id: 1,
    admission_date: '2026-01-30',
    contact_name: 'Henry Tan',
    contact_relationship: 'Spouse',
    contact_number: '09192228833',
  },
  {
    first_name: 'Lakshmi',
    middle_name: 'V.',
    last_name: 'Sharma',
    birthdate: '1988-08-08',
    birthplace: 'New Delhi, India',
    age: 37,
    sex: 'Female',
    address: 'Bonifacio Global City',
    religion: 'Hindu',
    ethnicity: 'Indian',
    chief_complaints: 'Anaphylaxis symptoms',
    room_no: 'ER-04',
    bed_no: '01',
    user_id: 1,
    admission_date: '2026-02-11',
    contact_name: 'Amit Sharma',
    contact_relationship: 'Husband',
    contact_number: '09556667788',
  },
  {
    first_name: 'Antonio',
    middle_name: 'Luna',
    last_name: 'Bautista',
    birthdate: '1945-12-25',
    birthplace: 'Vigan, Ilocos Sur',
    age: 80,
    sex: 'Male',
    address: 'Vigan, Ilocos Sur',
    religion: 'Roman Catholic',
    ethnicity: 'Ilocano',
    chief_complaints: 'Difficulty walking and hip pain',
    room_no: 'Geriatric-1',
    bed_no: '03',
    user_id: 1,
    admission_date: '2026-01-10',
    contact_name: 'Teresa Bautista',
    contact_relationship: 'Daughter',
    contact_number: '09173332211',
  },
  {
    first_name: 'Samantha',
    middle_name: 'Joy',
    last_name: 'Rivera',
    birthdate: '2003-02-14',
    birthplace: 'Quezon City',
    age: 23,
    sex: 'Female',
    address: 'UP Village, Diliman',
    religion: 'None',
    ethnicity: 'Tagalog',
    chief_complaints: 'Acute appendicitis',
    room_no: 'Surgical-3',
    bed_no: '09',
    user_id: 1,
    admission_date: '2026-03-02',
    contact_name: 'Mark Rivera',
    contact_relationship: 'Father',
    contact_number: '09087776655',
  },
  {
    first_name: 'Datu',
    middle_name: 'Bulas',
    last_name: 'Maling',
    birthdate: '1972-11-11',
    birthplace: 'Lake Sebu, South Cotabato',
    age: 53,
    sex: 'Male',
    address: 'Lake Sebu, South Cotabato',
    religion: 'Traditional',
    ethnicity: "T'boli",
    chief_complaints: 'Lower back injury',
    room_no: '202',
    bed_no: '10',
    user_id: 1,
    admission_date: '2026-02-05',
    contact_name: 'Sita Maling',
    contact_relationship: 'Wife',
    contact_number: '09664445566',
  },
  {
    first_name: 'Chloe',
    middle_name: 'Anne',
    last_name: 'Smith',
    birthdate: '2020-05-05',
    birthplace: 'Angeles City, Pampanga',
    age: 5,
    sex: 'Female',
    address: 'Clark, Pampanga',
    religion: 'Christian',
    ethnicity: 'Fil-Am',
    chief_complaints: 'Severe asthma attack',
    room_no: 'Pedia-ICU',
    bed_no: '02',
    user_id: 1,
    admission_date: '2026-01-25',
    contact_name: 'John Smith',
    contact_relationship: 'Father',
    contact_number: '09152221111',
  },
  {
    first_name: 'Hiroshi',
    middle_name: 'K.',
    last_name: 'Tanaka',
    birthdate: '1982-04-12',
    birthplace: 'Tokyo, Japan',
    age: 43,
    sex: 'Male',
    address: 'Sta. Rosa, Laguna',
    religion: 'Shinto',
    ethnicity: 'Japanese',
    chief_complaints: 'Food poisoning/Salmonella',
    room_no: '108',
    bed_no: 'B2',
    user_id: 1,
    admission_date: '2026-02-19',
    contact_name: 'Yumi Tanaka',
    contact_relationship: 'Sister',
    contact_number: '09328884455',
  },
  {
    first_name: 'Teresita',
    middle_name: 'D.',
    last_name: 'Reyes',
    birthdate: '1950-08-30',
    birthplace: 'Naga City',
    age: 75,
    sex: 'Female',
    address: 'Naga City, Camarines Sur',
    religion: 'Roman Catholic',
    ethnicity: 'Bicolano',
    chief_complaints: 'Dizziness and vertigo',
    room_no: '310',
    bed_no: '01',
    user_id: 1,
    admission_date: '2026-01-08',
    contact_name: 'Paul Reyes',
    contact_relationship: 'Grandson',
    contact_number: '09475551234',
  },
  {
    first_name: 'Leonardo',
    middle_name: 'Vinci',
    last_name: 'Castro',
    birthdate: '1999-01-01',
    birthplace: 'Baguio City',
    age: 27,
    sex: 'Male',
    address: 'Baguio City, Benguet',
    religion: 'Christian',
    ethnicity: 'Igorot',
    chief_complaints: 'Influenza-like symptoms',
    room_no: 'Isolation-1',
    bed_no: '01',
    user_id: 1,
    admission_date: '2026-02-22',
    contact_name: 'Gina Castro',
    contact_relationship: 'Aunt',
    contact_number: '09051119988',
  },
  {
    first_name: 'Ayesha',
    middle_name: 'M.',
    last_name: 'Khan',
    birthdate: '1991-10-10',
    birthplace: 'Islamabad, Pakistan',
    age: 34,
    sex: 'Female',
    address: 'Greenhills, San Juan',
    religion: 'Islam',
    ethnicity: 'Pakistani',
    chief_complaints: 'Kidney stones/colic',
    room_no: '415',
    bed_no: '04',
    user_id: 1,
    admission_date: '2026-01-18',
    contact_name: 'Zaid Khan',
    contact_relationship: 'Brother',
    contact_number: '09164448822',
  },
  {
    first_name: 'Pedro',
    middle_name: 'Penduko',
    last_name: 'Cruz',
    birthdate: '1980-03-03',
    birthplace: 'Caloocan City',
    age: 45,
    sex: 'Male',
    address: 'Caloocan North',
    religion: 'Roman Catholic',
    ethnicity: 'Tagalog',
    chief_complaints: 'Jaw pain and swelling',
    room_no: 'Dental-01',
    bed_no: 'N/A',
    user_id: 1,
    admission_date: '2026-02-12',
    contact_name: 'Luz Cruz',
    contact_relationship: 'Mother',
    contact_number: '09283334411',
  },
  {
    first_name: 'Maria',
    middle_name: 'Clara',
    last_name: 'De Los Santos',
    birthdate: '1995-12-12',
    birthplace: 'Manila',
    age: 30,
    sex: 'Female',
    address: 'Intramuros, Manila',
    religion: 'Roman Catholic',
    ethnicity: 'Spanish-Filipino',
    chief_complaints: 'Hyperemesis gravidarum',
    room_no: 'OB-Wait',
    bed_no: '05',
    user_id: 1,
    admission_date: '2026-03-01',
    contact_name: 'Crisostomo Ibarra',
    contact_relationship: 'Fiancé',
    contact_number: '09170001111',
  },
];

const YOUR_IP = '192.168.1.13'; //change this to match your current ip (ipconfig in cmd prompt)
const API_URL = 'http://' + YOUR_IP + ':8000/patients/';

async function runSeed() {
  console.log(`Starting seed process for ${patients.length} patients...`);

  for (let i = 0; i < patients.length; i++) {
    try {
      const response = await axios.post(API_URL, patients[i]);
      console.log(
        ` --[${i + 1}/${patients.length}] Success: ${patients[i].first_name} ${
          patients[i].last_name
        }`,
      );
    } catch (error) {
      console.error(
        ` --[${i + 1}/${patients.length}] Failed: ${
          patients[i].first_name
        }. Error: ${error.message}`,
      );
    }
  }

  console.log('Seeding complete!');
}

runSeed();
