import { StyleSheet, Platform } from 'react-native';

export const createStyles = (theme: any, isDarkMode: boolean) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: theme.background },
    scrollContent: { paddingHorizontal: 40, paddingBottom: 150 },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 25,
      marginTop: Platform.OS === 'ios' ? 20 : 40,
    },
    welcome: {
      fontSize: 35,
      color: theme.primary,
      fontFamily: 'MinionPro-SemiboldItalic',
    },
    date: {
      fontSize: 14,
      color: theme.textMuted,
      marginTop: 4,
      fontFamily: 'AlteHaasGroteskBold',
    },
    searchBarContainer: { marginBottom: 25, zIndex: 999 },
    searchBarWrapper: {
      backgroundColor: theme.card,
      borderRadius: 125,
      paddingHorizontal: 15,
      borderWidth: 0,
      height: 50,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    instructionContainer: { marginBottom: 25 },
    instructionText: {
      fontSize: 14,
      color: theme.textMuted,
      marginLeft: 5,
      fontFamily: 'AlteHaasGrotesk',
    },
    generateButton: {
      height: 48,
      backgroundColor: theme.buttonBg,
      borderRadius: 25,
      borderWidth: 1,
      borderColor: theme.buttonBorder,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 5,
      elevation: 2,
    },
    generateText: {
      color: theme.primary,
      fontFamily: 'AlteHaasGroteskBold',
      fontSize: 14,
      letterSpacing: 0.5,
    },
    blankSection: { height: 200 },
    loadingOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.65)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingLogo: {
      width: 90,
      height: 90,
      tintColor: '#ffffff',
      marginBottom: 20,
    },
    loadingText: {
      color: '#ffffff',
      fontSize: 14,
      fontFamily: 'AlteHaasGroteskBold',
      letterSpacing: 0.5,
    },
  });
