import { StyleSheet, Platform } from 'react-native';
export const createStyles = (theme: any, isDarkMode: boolean) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: theme.background },
    scrollContent: { paddingHorizontal: 40, paddingBottom: 150 },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 25,
      marginTop: Platform.OS === 'ios' ? 20 : 40,
    },
    welcome: {
      fontSize: 35,
      color: theme.primary,
      fontFamily: 'MinionPro-SemiboldItalic',
    },
    date: {
      fontSize: 14,
      color: theme.textMuted,
      marginTop: 4,
      fontFamily: 'AlteHaasGroteskBold',
    },
    searchContainer: { marginBottom: 25 },
    searchBarWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.card,
      borderRadius: 125,
      paddingHorizontal: 15,
      borderWidth: 0,
      height: 50,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    searchIcon: { marginRight: 10 },
    searchBar: {
      flex: 1,
      height: 50,
      color: theme.text,
      fontSize: 15,
      fontFamily: 'AlteHaasGrotesk',
    },
    listSection: { marginTop: -10 },
    patientCard: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 12,
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    patientLeft: { flexDirection: 'row', alignItems: 'center' },
    avatarPlaceholder: {
      width: 40,
      height: 40,
      borderRadius: 5,
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.border,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      marginLeft: 10,
    },
    info: { marginLeft: 15 },
    patientName: {
      fontFamily: 'AlteHaasGroteskBold',
      color: theme.text,
      fontSize: 15,
    },
    patientId: {
      fontFamily: 'AlteHaasGrotesk',
      color: theme.textMuted,
      fontSize: 12,
    },
  });

export const createModalStyles = (theme: any) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      width: '80%',
      maxHeight: '80%',
      backgroundColor: theme.background,
      borderRadius: 20,
      padding: 25,
      elevation: 15,
      borderWidth: 1.5,
      borderColor: theme.primary,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 25,
    },
    title: {
      fontSize: 24,
      color: theme.primary,
      fontFamily: 'AlteHaasGroteskBold',
      marginLeft: 5,
    },
    patientName: {
      fontSize: 16,
      color: theme.textMuted,
      fontFamily: 'AlteHaasGrotesk',
      marginLeft: 5,
    },
    closeButton: { padding: 5, marginTop: -5, marginRight: -5 },
    scrollContent: { paddingBottom: 10 },
    categoryCard: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: 'theme.card2',
      borderRadius: 18,
      padding: 10,
      marginBottom: 12,
      borderWidth: 0,
    },
    cardLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
    iconCircle: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.card,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
      marginLeft: 5,
    },
    cardInfo: { justifyContent: 'center', flex: 1 },
    categoryName: {
      fontSize: 16,
      fontFamily: 'AlteHaasGroteskBold',
      color: theme.primary,
    },
    updateText: {
      fontSize: 14,
      fontFamily: 'AlteHaasGrotesk',
      color: theme.textMuted,
      marginTop: 1,
    },
  });
